### ISSUE TITLE
Segmentation fault in jni_GetStaticMethodIDwhen creating client

### ISSUE THREAD

**Issue by benweint** [onddo/node-jmx#10]
Hello!

I'm seeing a repeatable segmentation fault when attempting to run the following script:

```javascript
#!/usr/bin/env node

var jmx = require('jmx');
var host = { host: 'localhost', port: 7511 }
var client = jmx.createClient(host)
``` 

The node process segfaults on the call to `createClient`. The crash creates a log file that can be seen in [this gist](https://gist.github.com/benweint/7e227d1f08e1bb8d0ebe).

Relevant version information:

* Ubuntu 14.04 on amd64
* Java:

```
$ java -version
java version "1.6.0_35"
OpenJDK Runtime Environment (IcedTea6 1.13.7) (6b35-1.13.7-1ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)
```

* `java` npm module: 0.5.4
* `jmx` npm module: 0.4.1

Here's the top of the stack extracted from the crash log:

```
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x53b09a]  get_method_id(JNIEnv_*, _jclass*, char const*, char const*, bool, Thread*) [clone .isra.108]+0x7a
V  [libjvm.so+0x53ee4d]  jni_GetStaticMethodID+0x7d
C  [nodejavabridge_bindings.node+0x1e551]  javaGetArgsForMethod(JNIEnv_*, _jobject*, _jarray*)+0x41
C  [nodejavabridge_bindings.node+0x1bd16]  InstanceMethodCallBaton::ExecuteInternal(JNIEnv_*)+0x36
C  [nodejavabridge_bindings.node+0x1bf6e]  MethodCallBaton::runSync()+0x1e
C  [nodejavabridge_bindings.node+0x17ae8]  JavaObject::methodCallSync(v8::Arguments const&)+0x178
```

Any ideas for how to debug this further?

**Comment by benweint** [comment]
Another note: this seems to have started happening with `jmx` 0.4.0. 0.3.1 works fine.

**Comment by zuazo** [comment]
I have no idea. `0.4.0` release updated `java` dependency from `~0.4.3` to `~0.5.0`.

Can you [report this issue to node java project](https://github.com/joeferner/node-java)?

**Comment by benweint** [comment]
Sure thing: https://github.com/joeferner/node-java/issues/238. I'm going to close this one out.

**Comment by zuazo** [comment]
Thanks @benweint. Tell me if you ever want to reopen this issue.
