### ISSUE TITLE
node-jmx can't run in node v4.2.1

### ISSUE THREAD

**Issue by redice** [onddo/node-jmx#11]
I encounter this problem, [failed node-java and node-jmx in node v4.2.1](http://is.gd/tZEliC)

But it works in my experiment,
update 
* node-java dependencies to [nan v2.1.0](https://github.com/nodejs/nan/releases/tag/v2.1.0)
* node-jmx dependencies to [node-java 0.6.0](https://github.com/joeferner/node-java/releases/tag/v0.6.0)

After that, node-java and node-jmx both work well in node v4.2.1.

Any plan to upgrade node-java dependencies?

**Comment by zuazo** [comment]
I fixed in master following your instructions.

谢谢！

**Comment by zuazo** [comment]
The nan version is only required if your are using old g++ versions.

Travis tests fixed in 3b63b249ea08768119943dfbafedeb1e33005a61.

**Comment by zuazo** [comment]
Fix released in version [`0.5.0`](https://github.com/zuazo/node-jmx/releases/tag/0.5.0).
