### ISSUE TITLE
JMX with jboss-client.jar

### ISSUE THREAD

**Issue by LucasScript** [onddo/node-jmx#5]
Is there a way to use the jboss-client.jar with jmx to connect to remote java server?

**Comment by zuazo** [comment]
Hello @LucasScript,

Unfortunately I'm not familiar with *jboss-client.jar*. I do not know what it is used for.

I think maybe it could be related to issue #4, that adds Weblogic JMX support. You could start with something like the following:

```javascript
java.classpath.push(path.resolve("jboss-client.jar"));
```

But I do not know if that will be enough.
