### ISSUE TITLE
[Feature Request] Adding support for getting multiple attributes ("client.getAttributes") in a single request

### ISSUE THREAD

**Issue by ericbroda** [onddo/node-jmx#6]
In situations where I wanted to monitor multiple attributes from a mbean, currently I need to issue "client.getAttribute" multiple times (once for each attribute).  While this is feasible, it requires multiple network calls.  Instead, I would like to issue a single request, "client.getAttributes", to retrieve multiple attributes.  This capability is already supported in JMX (java calls) and would enhance node-jmx capabilities.

**Comment by zuazo** [comment]
Implemented in #7. Closing.

**Comment by ericbroda** [comment]
Xabier,
Thank you very much for accepting the PR.   :-) 

When do you think the new package may be available via npm?
Best regards,
Eric Broda 


     On Wednesday, July 15, 2015 2:17 PM, Xabier de Zuazo <notifications@github.com> wrote:
   

 Implemented in #7. Closing.—

**Comment by zuazo** [comment]
During this week.

**Comment by zuazo** [comment]
Released in [`0.4.0`](https://github.com/onddo/node-jmx/releases/tag/0.4.0). Thank you for your patience :wink:
